/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MainProject;

import com.formdev.flatlaf.FlatDarkLaf;

import javax.swing.*;


public class App {
    public static void main(String[] args) throws UnsupportedLookAndFeelException {
        UIManager.setLookAndFeel(new FlatDarkLaf());
        new GUI();

    }
}
